database:
    driver: mysql
    host: localhost
    port: 3306
    name: testdb
    user: root
    password: 123456 # Use ENV_[YOUR ENVIRONMENT VARIABLE NAME] to load from environment variables.

project:
    migration_dir: ./migrations